# WE ARE STARTING NUMPY HERE

In [1]:
import numpy as np

In [2]:
myArray=np.array([[1,3,5,7,9]],np.int8)

In [3]:
myArray[0,1]

3

In [4]:
myArray.shape

(1, 5)

**ARRAY CREATION: CONVERSION FROM OTHER PYTHON STRUCTURES**

In [5]:
listArray=np.array([[1,2,3,],[4,5,6],[7,8,9]])

In [6]:
listArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
listArray.size

9

In [8]:
listArray.shape

(3, 3)

In [9]:
np.array({1,2,3,4,5})

array({1, 2, 3, 4, 5}, dtype=object)

In [10]:
zeros=np.zeros((2,6))

In [11]:
zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
rng=np.arange(15)

In [13]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
lspace=np.linspace(1,100,10)

In [15]:
lspace

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [16]:
emp=np.empty((2,6))

In [17]:
emp

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
emp_like=np.empty_like(lspace)

In [19]:
emp_like

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [20]:
ide=np.identity(5)

In [21]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
ide.shape

(5, 5)

In [23]:
arr=np.arange(10)

In [24]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr=arr.reshape(5,2)

In [26]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [27]:
arr=arr.ravel()

In [28]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr.shape

(10,)

In [30]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [31]:
ar=np.array(x)

In [32]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
ar.sum(axis=0)

array([12, 15, 18])

In [35]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [36]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [37]:
ar.flat

In [38]:
for item in ar.flat:
 print(item)

1
2
3
4
5
6
7
8
9


In [39]:
ar.ndim

2

In [40]:
ar.size

9

In [42]:
ar.nbytes

36

In [43]:
one=np.array([1,2,3,4,5,4,3,2])

In [44]:
one.argmax()

4

In [45]:
one.argmin()

0

In [46]:
one.argsort()

array([0, 1, 7, 2, 6, 3, 5, 4], dtype=int64)

In [47]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
ar.min()

1

In [50]:
ar.max()

9

In [55]:
y=np.where(ar>4)

In [56]:
y

(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))

In [57]:
type(y)

tuple

In [61]:
np.count_nonzero(ar)

9

In [63]:
import sys

In [64]:
py_ar=[1,2,3,44]


In [65]:
np_ar=np.array(py_ar)

In [67]:
sys.getsizeoff(1)*len(py_ar)

AttributeError: module 'sys' has no attribute 'getsizeoff'